apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: data-ingestion
    app.kubernetes.io/runtime: camel
    app.openshift.io/runtime: camel
  name: data-ingestion
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: data-ingestion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
