apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: data-ingestion
    app.kubernetes.io/runtime: camel
    app.openshift.io/runtime: camel
  name: data-ingestion
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: data-ingestion
  type: ClusterIP
